version: '3.7'

services:
  app:
    container_name: app
    image: app:latest
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
      args:
        - USERNAME
        - UID
        - GID
        - NODE_VER
        - PHP_VER
        - YARN_VER
    network_mode: "host"
  db:
    container_name: db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-docker}
      MYSQL_USER: ${MYSQL_USER:-docker}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    restart: on-failure
    network_mode: "host"
  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    network_mode: "host"
